### ISSUE TITLE
Videos don't play

### ISSUE THREAD

**Issue by voidless-03** [EugeneDae/VLC-Scheduler#1]
Nothing happens when the scheduled time comes. In the scheduler console it just says the video is playing, but does no display in vlc player. Any ideas?

**Comment by EugeneDae** [comment]
Could you please post your YAML config?

**Comment by voidless-03** [comment]
`sources:
    - path: F:/Videos/
      playing_time: 18:23-22:00
    

vlc:
    path: 'G:/Programs/VLC/vlc.exe'`

**Comment by voidless-03** [comment]
what version of vlc should i be using?

**Comment by EugeneDae** [comment]
Only VLC version 3.0 and higher are supported, version 4.0 has not been tested yet. 

Does VLC Scheduler launch VLC or do you launch by yourself?

**Comment by voidless-03** [comment]
I am using vlc 3.0.6. And yes the scheduler does launch vlc

**Comment by EugeneDae** [comment]
It works for me with VLC 3.0.6 on Windows 10. I'm clueless 🙁 Can you try a fresh install of VLC? Download VLC installer and while installing tick this:
![fresh](https://user-images.githubusercontent.com/980835/52080803-b7829580-25a9-11e9-8434-3d84ade16d60.png)

**Comment by ksavett** [comment]
I am having the same issues. Any ideas on how to fix this?

**Comment by EugeneDae** [comment]
@ksavett What happens exactly when you launch the program? Can you post a screenshot?

**Comment by ksavett** [comment]
![vlc](https://user-images.githubusercontent.com/14110870/62240812-c950c400-b3a5-11e9-9614-368c77f446cf.png)
![VLC2](https://user-images.githubusercontent.com/14110870/62240820-cd7ce180-b3a5-11e9-9791-effb25454f42.PNG)

**Comment by ksavett** [comment]
It says it is playing but no video plays within the media player.

**Comment by EugeneDae** [comment]
@ksavett You use a Unix-style path separator (slash) in Windows environment. What happens if you replace the slashes with backslashes in the paths specified in vlcscheduler.yaml? In other words, change: `C:/vids` to `C:\vids` and see what happens.

**Comment by ksavett** [comment]
Perfect! thanks for the help!

**Comment by EugeneDae** [comment]
@ksavett Thanks for taking time to report this, rather than simply ditching the program. I will update the code to avoid this issue.

**Comment by ksavett** [comment]
No thank you it is really a helpful tool. I appreciate your time.
