### ISSUE TITLE
Locating YAML file

### ISSUE THREAD

**Issue by 4thSpace** [EugeneDae/VLC-Scheduler#11]
Hello,

Very excited about the promise of VLC Scheduler.
Our YAML file is located in the same directory as the application, but on launch we are getting this error:
"FileNotFoundError: Cannot find the configuration file vlcscheduler.yaml in any of these places: /private/var/folders/69/f3vs7lnx55500pbdz4lx3r5h0000gr/T/AppTranslocation/8F0E6273-61CA-47F7-9A2C-6529700223B7/d/VLC Scheduler.app/Contents/MacOS/../../..."

Any advice is appreciated.

OsX10.13/VLC 3.04

**Comment by EugeneDae** [comment]
@4thSpace Apparently this is a new security feature in macOS, called "AppTranslocation", taking place.

Steps to solve the problem:

1. Open **Terminal.app.**
2. Copy the following command, but do NOT run it yet: `sudo xattr -r -d com.apple.quarantine`. 
3. Make sure to add a white space after `com.apple.quarantine`.
4. Now drag **VLC Scheduler.app** onto the Terminal window. The path to **VLC Scheduler.app** will appear at the end of the command, right after `com.apple.quarantine`, for example: `sudo xattr -r -d com.apple.quarantine /Users/bob/Desktop/VLC\ Scheduler.app`
5. Press Enter to run the command.

**Comment by 4thSpace** [comment]
That totally fixed it. Working fine now. A million thanks for the quick reply.
