### ISSUE TITLE
Often the yaml file is ignored

### ISSUE THREAD

**Issue by pavelmarko** [EugeneDae/VLC-Scheduler#13]
Even though my yaml file looks like this:
```
sources:
    - path: D:\OneDrive\Videos\Test

media_recursive: false

source_mixing_function: "chain"

image_play_duration: 5
```

When I run vlc-scheduler, sometimes it ignores those settings.

I confirmed this via debugging the source code and adding a breakpoint right after
`from config import config, logger` in vlcscheduler.py

![image](https://user-images.githubusercontent.com/52218852/60129558-922f3780-9795-11e9-9c32-aad290d574a2.png)

Four times out of ten my settings are ignored and config looks like this:
![image](https://user-images.githubusercontent.com/52218852/60129372-1f25c100-9795-11e9-8c9b-96ee45d01412.png)

While this is how it should look:
![image](https://user-images.githubusercontent.com/52218852/60129165-af173b00-9794-11e9-9628-e1e9c09df6fc.png)

I can't figure out what's causing this.
Help :) ?

**Comment by pavelmarko** [comment]
It was an issue with Pycharm, solved after a restart

**Comment by EugeneDae** [comment]
thank god, lol
